/* eslint-disable max-len */
export const dirtyField = 'FOA_number';
export const arrayData = ['123', 'test'];
export const preExistingStudyInfo = {
    studyId: 29,
    studyPropertyValues: [
        {
            id: 7935,
            value: 'phs002685',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 8098,
            value: 'DNA Star SAS-CoV-2 Rapid Test',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 10423,
            value: '10',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 8261,
            value: `A Novel Saliva-Based Aptamer Detection Assay for SARS-CoV-2 Infection (RFA-OD-20-021 STTR Application) Automated, rapid diagnostics with little sample collection and preparation are needed to identify and trace affected persons in times when hyper-infectious pathogens cause pandemics. Frequent, low cost and highly scalable testing is the only way to gain visibility on the magnitude of the pandemic and ultimately control the spread of the disease. We propose the development of a unique system that can cheaply and readily detect SARS-CoV-2 in saliva samples. The development of a system that uses saliva present an opportunity to readily test patients using a sample that is easily collected and harbors high concentration of viral particles. The 
  SARS-CoV-2 pandemic has predominantly affected individuals with pre-existing conditions such as clotting disorders, diabetes, hypertension or other chronic diseases. Patients with these pre-existing conditions who then are infected have exacerbated symptoms and complications that can lead to death. For example, many patients that have succumbed to SARS-CoV-2 infection have developed blood clots that have impaired pulmonary or cardiac function and ultimately cardiac failure. A rapid diagnostic using easily collected samples (e.g. saliva) would allow for infections to be identified sooner, 
  therapies to be administered quicker, treatment to be monitored, and ultimately leading to fewer individuals that succumb to the infection. We outline a novel DNA Star biosensing approach based on the fact that viruses, such as SARS- CoV-2, express unique spatial patterns of antigens on their surfaces, facilitating multivalent binding to 
  host cells for infection. These configurations of epitopes drive the high sensitivity and specificity of our assay. Based on this naturally occurring binding mechanism, we developed a rational design approach producing pattern matching designer DNA architecture for viral sensing. A proof-of-concept Dengue virus (DENV) rapid diagnostics was developed to demonstrate its power: DENV surface antigens present the most complex 
  geometric pattern among all known pathogens, a DNA star linked 10-aptamers nanostructure that offers polyvalent, spatial DENV- epitope pattern matching interactions has provided high DENV-binding avidity and specificity, increasing affinity by ~1,000× compared to the conventional aptamer approach which relies on monovalent aptamer-epitope interactions. Our POCT diagnostics detected intact DENV virions in patient samples with PCR equivalent sensitivity in <2 mins at a cost <$0.15. Current RT-PCR molecular 
  test are suited to large, centralized laboratories, and difficult to scale for rapid 
  testing of samples and delivery of results to clinicians and patients. Immunoassay tests have lower sensitivity, and patients need to develop a response to the virus in order to detect the antibody response. Our “DNA star” biosensor-based rapid diagnostics will provide the infrastructure for real time SARS-CoV-2 diagnostics that is easy to use (instrument-free), faster (sample to results in minutes) and cost effective (~$3 per test).`,
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 8582,
            value: 'RADx-rad',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35187,
            value: 'dbGaP',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35188,
            value: '123',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 9243,
            value: 'John Doe',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 9406,
            value: 'example@example.com',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35189,
            value: '11/11/1111',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 9569,
            value: 'Jane Doe',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 9721,
            value: 'example@example.com',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 9875,
            value: 'Atom Bioworks Inc',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35190,
            value: '12/31/2024',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 10036,
            value: '2021-10-29 00:00:00+00',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 10150,
            value: 'Dr. John Doe',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35191,
            value: '2019-nCoV',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 10574,
            value: 'Yes',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 10737,
            value: 'Yes',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 19787,
            value: 'Case Set',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35192,
            value: '123',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13001,
            value: 'Saliva',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13392,
            value: 'The study was funded by NIH support 1R44DE030852-01',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 14366,
            value: 'RADx Data Hub',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 14639,
            value: 'Existing (Legacy)',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 14751,
            value: 'Yes',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 14914,
            value: 'Non-Human Data',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 15233,
            value: 'timeline',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 15389,
            value: 'Data will be deposited quarterly after first data submission.',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 15711,
            value: 'General Research Use',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 15989,
            value: '1R44DE030852-01',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 16152,
            value: 'Yes',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 16944,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 9027,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 11082,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13066,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13229,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13551,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13714,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 13877,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 14040,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 14203,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 16315,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 16480,
            value: 'No',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 17023,
            value: 'COVID Testing Device',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 17562,
            value: 'NIH OD',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 17758,
            value: 'Qualitative data',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 17759,
            value: 'data from instrument development',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 18393,
            value: '0.1',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 30461,
            value: '1 - 250',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 15526,
            value: '11/11/2024',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
        {
            id: 35193,
            value: 'dbVar',
            entityProperty: [Object],
            valueIndex: null,
            shouldBeRemoved: false,
        },
    ],
};
export const formFields = {
    title: 'DNA Star SAS-CoV-2 Rapid Test',
    has_ic: 'No',
    data_sharing_info: 'Yes',
    estimated_participants: '10',
    is_multi_center: 'No',
    multi_center_sites: '',
    data_access_points_other: [],
    data_submission_date: '',
    data_submission_timeline_details: 'Data will be deposited quarterly after first data submission.',
    data_target_delivery_date: '11/11/2024',
    data_storage_size: '0.1',
    pi_name: 'John Doe',
    pi_email: 'example@example.com',
    pi_institution: 'Atom Bioworks Inc',
    pi_assistant_name: 'Jane Doe',
    pi_assistant_email: 'example@example.com',
    grant_number: ['1R44DE030852-01'],
    po_name: 'Dr. John Doe',
    types_other_specify: [],
    data_general_types_other_specify: [],
    data_genomic_other_specify: [],
    data_phenotype_other_specify: [],
    data_sample_types_other_specify: [],
    data_genotype_other_specify: [],
    data_sequencing_other_specify: [],
    data_analyses_other_specify: [],
    data_array_data_other_specify: [],
    acknowledgement_statement: 'The study was funded by NIH support 1R44DE030852-01',
    description: `A Novel Saliva-Based Aptamer Detection Assay for SARS-CoV-2 Infection (RFA-OD-20-021 STTR Application) Automated, rapid diagnostics with little sample collection and preparation are needed to identify and trace affected persons in times when hyper-infectious pathogens cause pandemics. Frequent, low cost and highly scalable testing is the only way to gain visibility on the magnitude of the pandemic and ultimately control the spread of the disease. We propose the development of a unique system that can cheaply and readily detect SARS-CoV-2 in saliva samples. The development 
  of a system that uses saliva present an opportunity to readily test patients using a 
  sample that is easily collected and harbors high concentration of viral particles. The SARS-CoV-2 pandemic has predominantly affected individuals with pre-existing conditions such as clotting disorders, diabetes, hypertension or other chronic diseases. Patients with these pre-existing conditions who then are infected have exacerbated symptoms and complications that can lead to death. For example, many patients that have succumbed to SARS-CoV-2 infection have developed blood clots that have impaired pulmonary or cardiac function and ultimately cardiac failure. A rapid diagnostic using easily collected samples (e.g. saliva) would allow for infections to be identified sooner, therapies to be administered quicker, treatment to be monitored, and ultimately leading to fewer individuals that succumb to the infection. We outline a novel DNA Star 
  biosensing approach based on the fact that viruses, such as SARS- CoV-2, express unique spatial patterns of antigens on their surfaces, facilitating multivalent binding to host cells for infection. These configurations of epitopes drive the high sensitivity and specificity of our assay. Based on this naturally occurring binding mechanism, we developed a rational design approach producing pattern matching designer DNA architecture for viral sensing. A proof-of-concept Dengue virus (DENV) rapid diagnostics 
  was developed to demonstrate its power: DENV surface antigens present the most complex geometric pattern among all known pathogens, a DNA star linked 10-aptamers nanostructure that offers polyvalent, spatial DENV- epitope pattern matching interactions has provided high DENV-binding avidity and specificity, increasing affinity by ~1,000× compared to the conventional aptamer approach which relies on monovalent aptamer-epitope interactions. Our POCT diagnostics detected intact DENV virions in patient samples with PCR equivalent sensitivity in <2 mins at a cost <$0.15. Current RT-PCR molecular test are suited to large, centralized laboratories, and difficult to scale for rapid testing of samples and delivery of results to clinicians and patients. Immunoassay 
  tests have lower sensitivity, and patients need to develop a response to the virus in order to detect the antibody response. Our “DNA star” biosensor-based rapid diagnostics will provide the infrastructure for real time SARS-CoV-2 diagnostics that is easy to use (instrument-free), faster (sample to results in minutes) and cost effective (~$3 per test).`,
    disease_specific_related_conditions: '',
    other_group_description: '',
    data_access_points: [
        { label: 'dbGaP', value: 'dbGaP' },
        { label: 'RADx Data Hub', value: 'RADx Data Hub' },
        { label: 'dbVar', value: 'dbVar' },
    ],
    institutes_supporting_study: [{ label: 'NIH OD', value: 'NIH OD' }],
    types: [{ label: 'Case Set', value: 'Case Set' }],
    data_species: [{ label: 'Non-Human Data', value: 'Non-Human Data' }],
    data_sample_collection: [{ label: 'Existing (Legacy)', value: 'Existing (Legacy)' }],
    data_general_types: [
        { label: 'Qualitative data', value: 'Qualitative data' },
        {
            label: 'data from instrument development',
            value: 'data from instrument development',
        },
    ],
    data_genomic: [],
    data_phenotype: [],
    data_sample_types: [{ label: 'Saliva', value: 'Saliva' }],
    data_genotype: [],
    data_sequencing: [],
    data_analyses: [],
    data_array_data: [],
    general_research_group: [{ label: 'General Research Use', value: 'General Research Use' }],
    health_biomed_group: [],
    disease_specific_group: [],
    FOA_number: ['123', 'test'],
    studystartdate: '11/11/1111',
    studyenddate: '12/31/2024',
    topics_other_specify: [],
    source_other_specify: [],
    subject: ['123'],
    CT_URL: '',
    study_website_URL: '',
    publication_URL: [],
    topics: [{ label: '2019-nCoV', value: '2019-nCoV' }],
    source: [{ label: 'COVID Testing Device', value: 'COVID Testing Device' }],
};
export const i = 52;
export const entityProperties = [
    { id: 1, name: 'phs' },
    { id: 2, name: 'title' },
    { id: 6, name: 'studystartdate' },
    { id: 7, name: 'studyenddate' },
    { id: 5, name: 'dcc' },
    { id: 20, name: 'source' },
    { id: 3, name: 'description' },
    { id: 8, name: 'is_multi_center' },
    { id: 9, name: 'multi_center_sites' },
    { id: 10, name: 'pi_name' },
    { id: 18, name: 'estimated_participants' },
    { id: 36, name: 'aggregate_appropriate_for_general_use' },
    { id: 38, name: 'consent_to_add_aggregate' },
    { id: 39, name: 'consent_to_add_individual' },
    { id: 42, name: 'data_access_points' },
    { id: 43, name: 'data_analyses' },
    { id: 45, name: 'data_from_repository_name' },
    { id: 46, name: 'data_phenotype' },
    { id: 47, name: 'data_sample_collection' },
    { id: 48, name: 'data_sharing_info' },
    { id: 50, name: 'data_storage_size' },
    { id: 51, name: 'data_submission_date' },
    { id: 52, name: 'data_submission_method' },
    { id: 53, name: 'data_submission_timeline_details' },
    { id: 54, name: 'data_target_delivery_date' },
    { id: 55, name: 'data_target_release_date' },
    { id: 61, name: 'geno_seq_platform_info' },
    { id: 62, name: 'geno_seq_platform_url' },
    { id: 63, name: 'geno_seq_platform_probes' },
    { id: 64, name: 'geno_seq_platform_vendor' },
    { id: 65, name: 'geno_seq_platform_description' },
    { id: 66, name: 'geno_seq_platform_name_version' },
    { id: 68, name: 'has_era_account' },
    { id: 69, name: 'has_ic' },
    { id: 71, name: 'individual_appropriate_for_general_use' },
    { id: 72, name: 'other_group_description' },
    { id: 26, name: 'data_general_types' },
    { id: 44, name: 'data_array_data' },
    { id: 24, name: 'institutes_supporting_study' },
    { id: 22, name: 'types' },
    { id: 35, name: 'acknowledgement_statement' },
    { id: 67, name: 'grant_number' },
    { id: 60, name: 'general_research_group' },
    { id: 70, name: 'health_biomed_group' },
    { id: 57, name: 'disease_specific_related_conditions' },
    { id: 49, name: 'data_species' },
    { id: 83, name: 'types_other_specify' },
    { id: 91, name: 'data_analyses_other_specify' },
    { id: 17, name: 'officer_sign_date' },
    { id: 25, name: 'needs_institutional_certifications' },
    { id: 11, name: 'pi_email' },
    { id: 12, name: 'pi_assistant_name' },
    { id: 13, name: 'pi_assistant_email' },
    { id: 15, name: 'pi_sign_date' },
    { id: 16, name: 'po_name' },
    { id: 27, name: 'data_genomic' },
    { id: 28, name: 'data_genotype' },
    { id: 29, name: 'data_sample_types' },
    { id: 30, name: 'data_sequencing' },
    { id: 56, name: 'disease_specific_group' },
    { id: 14, name: 'pi_institution' },
    { id: 85, name: 'data_general_types_other_specify' },
    { id: 86, name: 'data_genomic_other_specify' },
    { id: 87, name: 'data_phenotype_other_specify' },
    { id: 88, name: 'data_sample_types_other_specify' },
    { id: 89, name: 'data_genotype_other_specify' },
    { id: 90, name: 'data_sequencing_other_specify' },
    { id: 92, name: 'data_array_data_other_specify' },
    { id: 84, name: 'source_other_specify' },
    { id: 21, name: 'subject' },
    { id: 100, name: 'FOA_number' },
    { id: 101, name: 'FOA_URL' },
    { id: 95, name: 'study_website_URL' },
    { id: 97, name: 'publication_URL' },
    { id: 82, name: 'topics' },
    { id: 98, name: 'access_type' },
    { id: 99, name: 'data_access_type' },
    { id: 102, name: 'estimated_participant_range' },
    { id: 96, name: 'CT_URL' },
    { id: 93, name: 'data_access_points_other' },
    { id: 94, name: 'topics_other_specify' },
];
