export const propsBody = {
    Title: [{ entityPropertyName: 'title', displayLabel: 'title' }],
    Representative: [
        { entityPropertyName: 'phs', displayLabel: 'phs' },
        { entityPropertyName: 'description', displayLabel: 'description' },
        { entityPropertyName: 'dcc', displayLabel: 'dcc' },
        { entityPropertyName: 'pi_name', displayLabel: 'pi_name' },
        { entityPropertyName: 'pi_email', displayLabel: 'pi_email' },
        { entityPropertyName: 'public_access_data', displayLabel: 'subject' },
        { entityPropertyName: 'subject', displayLabel: 'types' },
        { entityPropertyName: 'data_general_types', displayLabel: 'data_general_types' },
        { entityPropertyName: 'data_genomic', displayLabel: 'data_genomic' },
        { entityPropertyName: 'data_genotype', displayLabel: 'data_genotype' },
        { entityPropertyName: 'data_sample_types', displayLabel: 'data_sample_types' },
    ],
    Detail: [
        { entityPropertyName: 'status', displayLabel: 'status' },
        { entityPropertyName: 'studystartdate', displayLabel: 'studystartdate' },
        { entityPropertyName: 'studyenddate', displayLabel: 'studyenddate' },
        { entityPropertyName: 'is_multi_center', displayLabel: 'is_multi_center' },
        { entityPropertyName: 'multi_center_sites', displayLabel: 'multi_center_sites' },
        { entityPropertyName: 'pi_assistant_name', displayLabel: 'pi_assistant_email' },
        { entityPropertyName: 'pi_assistant_email', displayLabel: 'pi_institution' },
        { entityPropertyName: 'pi_institution', displayLabel: 'pi_sign_date' },
        { entityPropertyName: 'pi_sign_date', displayLabel: 'po_name' },
        { entityPropertyName: 'po_name', displayLabel: 'estimated_participants' },
        { entityPropertyName: 'officer_sign_date', displayLabel: 'public_access_data' },
        { entityPropertyName: 'estimated_participants', displayLabel: 'source' },
        { entityPropertyName: 'source', displayLabel: 'pi_assistant_name' },
        { entityPropertyName: 'types', displayLabel: 'unrestricted_access' },
        { entityPropertyName: 'unrestricted_access', displayLabel: 'institutes_supporting_study' },
        { entityPropertyName: 'institutes_supporting_study', displayLabel: 'needs_institutional_certifications' },
        { entityPropertyName: 'needs_institutional_certifications', displayLabel: 'officer_sign_date' },
        { entityPropertyName: 'data_sequencing', displayLabel: 'data_sequencing' },
    ],
};
