/* eslint-disable max-len */

export const searchBody = {
    internalResponse: {
        numReducePhases: 1,
        fragment: true,
    },
    scrollId: null,
    totalShards: 5,
    successfulShards: 5,
    skippedShards: 0,
    shardFailures: [],
    clusters: {
        total: 0,
        successful: 0,
        skipped: 0,
        fragment: true,
    },
    hits: {
        hits: [
            {
                score: 1,
                id: '6ibYJ4kBcyt0zD4LTkw0',
                type: null,
                nestedIdentity: null,
                version: -1,
                seqNo: -2,
                primaryTerm: 0,
                highlightFields: {},
                sortValues: [],
                matchedQueries: [],
                explanation: null,
                shard: null,
                sourceAsMap: {
                    data_genotype: null,
                    studyenddate: null,
                    pi_name: 'John Doe',
                    dcc: 'RADx-rad',
                    unrestricted_access: 'National Institute of Dental and Craniofacial Research (NIDCR) at NIH',
                    pi_email: 'example@example.com',
                    subject: 'Study Development',
                    description:
                        'This study is designed to develop aptamer-based electrochemical detection platform with SARS-CoV-2 as the model system to demonstrate performance.\n\nAs this study is a technology development,  the data generate do not involve anything related to human samples or human subjects. The project’s goals will be relayed as a data summary in the form of a presentation recapping the study journey and performance characteristics including: LOD, sensitivity, specificity, throughput, etc. of the minimal viable prototype platform developed as a result of this technology-based development project supported by the NIH.',
                    pi_sign_date: 'Dr. John Doe',
                    source: 'Dr. Jane Doe',
                    study_id: 110,
                    title: 'Direct Bioelectronic Detection of SARS-Cov-2 from Saliva using Singlemolecule Field-effect Transistor Array',
                    data_sequencing: null,
                    public_access_data: null,
                    estimated_participants: null,
                    '@version': '1',
                    po_name: null,
                    data_general_types:
                        'LOD, sensitivity, specificity, throughput, etc. of the minimal viable prototype platform developed as a result of this technology-based development project supported by the NIH.',
                    needs_institutional_certifications: null,
                    types: 'true',
                    multi_center_sites: null,
                    pi_assistant_name: 'example@example.com',
                    pi_institution: null,
                    data_sample_types: null,
                    institutes_supporting_study: 'false',
                    '@timestamp': '2023-07-05T20:57:13.198Z',
                    is_multi_center: 'false',
                    pi_assistant_email: 'mPOD, Inc.',
                    phs: 'phs002702',
                    officer_sign_date: 'true',
                    studystartdate: null,
                    data_genomic: null,
                    status: 'draft',
                },
                innerHits: null,
                fields: {},
                index: 'study_v002',
                clusterAlias: null,
                sourceAsString:
                    '{"is_multi_center":"false","studystartdate":null,"estimated_participants":null,"public_access_data":null,"@version":"1","pi_assistant_name":"example@example.com","types":"true","status":"draft","pi_name":"John Doe","pi_assistant_email":"mPOD, Inc.","dcc":"RADx-rad","pi_email":"example@example.com","@timestamp":"2023-07-05T20:57:13.198Z","phs":"phs002702","pi_sign_date":"Dr. John Doe","po_name":null,"data_genotype":null,"source":"Dr. Jane Doe","data_sample_types":null,"officer_sign_date":"true","title":"A scalable aptamer-based electrochemical biosensor for rapid detection of SARS-CoV-2 from saliva","unrestricted_access":"National Institute of Dental and Craniofacial Research (NIDCR) at NIH","pi_institution":null,"data_general_types":"LOD, sensitivity, specificity, throughput, etc. of the minimal viable prototype platform developed as a result of this technology-based development project supported by the NIH.","multi_center_sites":null,"study_id":110,"needs_institutional_certifications":null,"description":"This study is designed to develop aptamer-based electrochemical detection platform with SARS-CoV-2 as the model system to demonstrate performance.\\n\\nAs this study is a technology development,  the data generate do not involve anything related to human samples or human subjects. The project’s goals will be relayed as a data summary in the form of a presentation recapping the study journey and performance characteristics including: LOD, sensitivity, specificity, throughput, etc. of the minimal viable prototype platform developed as a result of this technology-based development project supported by the NIH.","studyenddate":null,"data_genomic":null,"institutes_supporting_study":"false","subject":"Study Development","data_sequencing":null}',
                rawSortValues: [],
                sourceRef: {
                    fragment: true,
                },
                fragment: false,
            },
            {
                score: 1,
                id: 'BCbYJ4kBcyt0zD4LTk2f',
                type: null,
                nestedIdentity: null,
                version: -1,
                seqNo: -2,
                primaryTerm: 0,
                highlightFields: {},
                sortValues: [],
                matchedQueries: [],
                explanation: null,
                shard: null,
                sourceAsMap: {
                    data_genotype: null,
                    studyenddate: null,
                    pi_name: 'John Doe',
                    dcc: 'Digital Health Technologies',
                    unrestricted_access: 'NIH/NCI/NIBIB',
                    pi_email: 'example@example.com',
                    subject: null,
                    description:
                        'The purpose of the Digital Health Solutions for COVID-19 study was to investigate the feasibility of digital health solutions to provide SARS-CoV-2, the causative agent for COVID-19, related de-identified data to the NIH-sponsored data hub through the ‘hub and spoke’ model.  Once in operation, the data distribution model will consist of a centralized architecture in which selected digital health solutions - the spokes - can transmit participant de-identified data to be used by the scientific community for COVID-19 research.  The complete study will include 300 participants 100% medically underserved with at least 51% from the AI/AN community. A combination of hard and soft data will be collected consisting of vital data, medical history and questionnaire data, and participant COVID-19 viral and antibody testing results collected during the study.',
                    pi_sign_date: 'John Doe',
                    source: 'Jane Doe',
                    study_id: 35,
                    title: 'RADx DATA SHARING PLAN AND SUBMISSION INFORMATION FINAL_AJK',
                    data_sequencing: null,
                    public_access_data: null,
                    estimated_participants: null,
                    '@version': '1',
                    po_name: '300',
                    data_general_types: 'Social, Questionnaires/Surveys',
                    needs_institutional_certifications: null,
                    types: 'false',
                    multi_center_sites: null,
                    pi_assistant_name: 'example@example.com',
                    pi_institution: '2021-01-18 00:00:00+00',
                    data_sample_types: null,
                    institutes_supporting_study: 'false',
                    '@timestamp': '2023-07-05T20:57:13.170Z',
                    is_multi_center: 'false',
                    pi_assistant_email: 'Jane Doe',
                    phs: 'phs002534',
                    officer_sign_date: 'false',
                    studystartdate: null,
                    data_genomic: null,
                    status: 'approved',
                },
                innerHits: null,
                fields: {},
                index: 'study_v002',
                clusterAlias: null,
                sourceAsString:
                    '{"is_multi_center":"false","studystartdate":null,"estimated_participants":null,"public_access_data":null,"@version":"1","pi_assistant_name":"example@example.com","types":"false","status":"approved","pi_name":"John Doe","pi_assistant_email":"Jane Doe","dcc":"Digital Health Technologies","pi_email":"example@example.com","@timestamp":"2023-07-05T20:57:13.170Z","phs":"phs002534","pi_sign_date":"Andrew Kurtz","po_name":"300","data_genotype":null,"source":"Jane Doe","data_sample_types":null,"officer_sign_date":"false","title":"RADx DATA SHARING PLAN AND SUBMISSION INFORMATION FINAL_AJK","unrestricted_access":"NIH/NCI/NIBIB","pi_institution":"2021-01-18 00:00:00+00","data_general_types":"Social, Questionnaires/Surveys","multi_center_sites":null,"study_id":35,"needs_institutional_certifications":null,"description":"The purpose of the Digital Health Solutions for COVID-19 study was to investigate the feasibility of digital health solutions to provide SARS-CoV-2, the causative agent for COVID-19, related de-identified data to the NIH-sponsored data hub through the ‘hub and spoke’ model.  Once in operation, the data distribution model will consist of a centralized architecture in which selected digital health solutions - the spokes - can transmit participant de-identified data to be used by the scientific community for COVID-19 research.  The complete study will include 300 participants 100% medically underserved with at least 51% from the AI/AN community. A combination of hard and soft data will be collected consisting of vital data, medical history and questionnaire data, and participant COVID-19 viral and antibody testing results collected during the study.","studyenddate":null,"data_genomic":null,"institutes_supporting_study":"false","subject":null,"data_sequencing":null}',
                rawSortValues: [],
                sourceRef: {
                    fragment: true,
                },
                fragment: false,
            },
            {
                score: 1,
                id: 'CybYJ4kBcyt0zD4LTk2f',
                type: null,
                nestedIdentity: null,
                version: -1,
                seqNo: -2,
                primaryTerm: 0,
                highlightFields: {},
                sortValues: [],
                matchedQueries: [],
                explanation: null,
                shard: null,
                sourceAsMap: {
                    data_genotype: null,
                    studyenddate: '10/31/2022',
                    pi_name: 'Jane Doe',
                    dcc: 'RADx-UP',
                    unrestricted_access: 'NIMHHD',
                    pi_email: 'example@example.com',
                    subject: 'Longitudinal Cohort Study',
                    description:
                        'The investigators at Xavier University of Louisiana are utilizing a multicenter approach including clinic, health care institution, and community survey-based research project to\rassess the beliefs and behavior regarding willingness to be vaccinated with a prospective COVID-19 vaccine among African Americans in the Southeastern Louisiana region. The\rCOVID-19 pandemic has disproportionately impacted the African American across the United States. Louisiana ranks 1st in the nation in per capita incidence of COVID-19. African\rAmericans make up over 50% of the deaths of all known COVID-19 patients in the state, while only representing about 32% of the population. With the development of a COVID-19\rvaccine on the near horizon, an urgent assessment of the African American community’s readiness for vaccine uptake is needed to inform a pharmacist-led intervention model that\rwill increase vaccine uptake. The Specific Aims of this proposal are:\rSpecific Aim #1: To identify factors of vaccine hesitancy and the potential acceptance of a COVID-19 vaccine among the adult African-American community in Southeastern\rLouisiana.\rSpecific Aim #2: To assess the personal and financial impact of COVID-19, knowledge of COVID-19, as well as experience with the healthcare system with regards to COVID-19.\rSpecific Aim #3: To use the results of Aim #1 and #2 to inform a community pharmacist certification course and a pharmacist led intervention model among pharmacist vaccinators.\rMethod: Specific Aim #1 and #2 will be assessed by a survey at the start of study with an abbreviated follow-up survey 9 months later from clinic, community member and\rcommunity pharmacy patient respondents. Changes in vaccine hesitancy and the impact on vaccine uptake will be determined.\rAim#3 will be assessed by a pharmacist led education intervention model with vaccine uptake surveillance in community pharmacies across Louisiana to assess COVID-19 and\rother ACIP eligible vaccines.\rImpact: The implications of this proposed project are to understand health related beliefs and behaviors related to COVID-19 and vaccination and their impact on the likely uptake of\ra COVID-19 vaccine among African Ameircans. It will also provide data to facilitate the development of strategies',
                    pi_sign_date: 'Jane Doe',
                    source: 'John Doe',
                    study_id: 155,
                    title: 'Assessing Vaccine Hesitancy and a Pharmacist Led Intervention Model to Increase COVID-19 Vaccine Uptake Among African Americans',
                    data_sequencing: null,
                    public_access_data: 'Human Data; Behavioral; Family History; Questionnaires/Surveys; Social',
                    estimated_participants: 'Survey',
                    '@version': '1',
                    po_name: '487',
                    data_general_types: 'Behavioral, Family History, Social, Questionnaires/Surveys',
                    needs_institutional_certifications: null,
                    types: 'false',
                    multi_center_sites: null,
                    pi_assistant_name: 'example@example.com',
                    pi_institution: null,
                    data_sample_types: null,
                    institutes_supporting_study: 'true',
                    '@timestamp': '2023-07-05T20:57:13.209Z',
                    is_multi_center: 'false',
                    pi_assistant_email: 'John Doe',
                    phs: 'phs002875',
                    officer_sign_date: 'false',
                    studystartdate: '11/01/2020',
                    data_genomic: null,
                    status: 'approved',
                },
                innerHits: null,
                fields: {},
                index: 'study_v002',
                clusterAlias: null,
                sourceAsString:
                    '{"is_multi_center":"false","studystartdate":"11/01/2020","estimated_participants":"Survey","public_access_data":"Human Data; Behavioral; Family History; Questionnaires/Surveys; Social","@version":"1","pi_assistant_name":"example@example.com","types":"false","status":"approved","pi_name":"Jane Doe","pi_assistant_email":"John Doe","dcc":"RADx-UP","pi_email":"example@example.com","@timestamp":"2023-07-05T20:57:13.209Z","phs":"phs002875","pi_sign_date":"Jane Doe","po_name":"487","data_genotype":null,"source":"Jane Doe","data_sample_types":null,"officer_sign_date":"false","title":"Assessing Vaccine Hesitancy and a Pharmacist Led Intervention Model to Increase COVID-19 Vaccine Uptake Among African Americans","unrestricted_access":"NIMHHD","pi_institution":null,"data_general_types":"Behavioral, Family History, Social, Questionnaires/Surveys","multi_center_sites":null,"study_id":155,"needs_institutional_certifications":null,"description":"The investigators at Xavier University of Louisiana are utilizing a multicenter approach including clinic, health care institution, and community survey-based research project to\\rassess the beliefs and behavior regarding willingness to be vaccinated with a prospective COVID-19 vaccine among African Americans in the Southeastern Louisiana region. The\\rCOVID-19 pandemic has disproportionately impacted the African American across the United States. Louisiana ranks 1st in the nation in per capita incidence of COVID-19. African\\rAmericans make up over 50% of the deaths of all known COVID-19 patients in the state, while only representing about 32% of the population. With the development of a COVID-19\\rvaccine on the near horizon, an urgent assessment of the African American community’s readiness for vaccine uptake is needed to inform a pharmacist-led intervention model that\\rwill increase vaccine uptake. The Specific Aims of this proposal are:\\rSpecific Aim #1: To identify factors of vaccine hesitancy and the potential acceptance of a COVID-19 vaccine among the adult African-American community in Southeastern\\rLouisiana.\\rSpecific Aim #2: To assess the personal and financial impact of COVID-19, knowledge of COVID-19, as well as experience with the healthcare system with regards to COVID-19.\\rSpecific Aim #3: To use the results of Aim #1 and #2 to inform a community pharmacist certification course and a pharmacist led intervention model among pharmacist vaccinators.\\rMethod: Specific Aim #1 and #2 will be assessed by a survey at the start of study with an abbreviated follow-up survey 9 months later from clinic, community member and\\rcommunity pharmacy patient respondents. Changes in vaccine hesitancy and the impact on vaccine uptake will be determined.\\rAim#3 will be assessed by a pharmacist led education intervention model with vaccine uptake surveillance in community pharmacies across Louisiana to assess COVID-19 and\\rother ACIP eligible vaccines.\\rImpact: The implications of this proposed project are to understand health related beliefs and behaviors related to COVID-19 and vaccination and their impact on the likely uptake of\\ra COVID-19 vaccine among African Ameircans. It will also provide data to facilitate the development of strategies","studyenddate":"10/31/2022","data_genomic":null,"institutes_supporting_study":"true","subject":"Longitudinal Cohort Study","data_sequencing":null}',
                rawSortValues: [],
                sourceRef: {
                    fragment: true,
                },
                fragment: false,
            },
            {
                score: 1,
                id: 'DSbYJ4kBcyt0zD4LTk2f',
                type: null,
                nestedIdentity: null,
                version: -1,
                seqNo: -2,
                primaryTerm: 0,
                highlightFields: {},
                sortValues: [],
                matchedQueries: [],
                explanation: null,
                shard: null,
                sourceAsMap: {
                    data_genotype: null,
                    studyenddate: '06/30/2022',
                    pi_name: 'John Doe',
                    dcc: 'RADx-UP',
                    unrestricted_access: 'NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES',
                    pi_email: 'example@example.com',
                    subject:
                        'This is a randomized vaccine hesitancy intervention conducted in churches by church health ministers We will collect data from surveys and SARS-CoV-2 testing',
                    description:
                        'In the US, COVID-19 unveiled a disproportionate health burden in low income and underserved segments of society.  In Louisiana, some of the greatest health and economic consequences are evident in our Black communities. Furthermore, despite the widespread availability of SARS-CoV-2 vaccines, approximately 30% of the US population reports that they will not get vaccinated, and Black citizens and those with lower socio-economic status are more likely to have vaccine hesitancy. Thus, there is an urgent need to address vaccine hesitancy within the context of the COVID-19 pandemic and the current testing environment. The Louisiana Clinical and Translational Science (LA CaTS) Center provides the essential infrastructure and key foundational support for biomedical research in our region and is uniquely positioned to lead a community-engaged research project to determine solutions to decrease vaccine hesitancy and improve testing rates in our most underserved populations. Faith-based organizations (churches, mosques, temples, etc.) are trusted sources of information, especially among Black communities, and may represent an opportunity to convey accurate, unbiased health information regarding COVID-19 vaccinations and testing to the community. Many Black churches have well-developed health ministries that integrate faith and health for their members and the communities they serve. We will use a mixed-methods study design to determine the effectiveness of training church health ministers to educate their congregations about the safety and efficacy of COVID-19 vaccines for decreasing vaccine hesitancy and improving testing knowledge in underserved Black communities. We will randomize 98 participants from five churches to an intervention group that will receive counseling from their health ministers on the benefits of getting vaccinated and tested, or to a delayed intervention control group. The effects of the intervention on the primary outcome, vaccine hesitancy measured by a questionnaire, will be administered to both groups after three weeks. Following the three-week control period, the delayed intervention control group will also receive the intervention and again be administered the questionnaire. We will then conduct focus groups among a sub-sample of participants to obtain more granular information on sources of vaccine hesitancy and for their vaccine-related decisions. The achievement of the study’s goals will significantly increase our understanding of vaccine hesitancy within Black urban communities in Louisiana. Our results will inform the development of targeted interventions to increase vaccine coverage in the large, underserved populations across the American South.',
                    pi_sign_date: 'Jane Doe',
                    source: 'Jane Doe',
                    study_id: 189,
                    title: 'Engaging Church Health Ministries to Decrease SARS-CoV-2 Vaccine Hesitancy in Underserved Populations in Baton Rouge',
                    data_sequencing: null,
                    public_access_data: 'Human Data; Prospective Sample; Questionnaires/Surveys; SARS-CoV-2 test result',
                    estimated_participants: 'Survey',
                    '@version': '1',
                    po_name: '98',
                    data_general_types: 'Questionnaires/Surveys, SARS-CoV-2 test result',
                    needs_institutional_certifications: null,
                    types: 'false',
                    multi_center_sites: null,
                    pi_assistant_name: 'example@example.com',
                    pi_institution: null,
                    data_sample_types: null,
                    institutes_supporting_study: 'true',
                    '@timestamp': '2023-07-05T20:57:13.218Z',
                    is_multi_center: 'false',
                    pi_assistant_email: 'Pennington Biomedical Research Center',
                    phs: 'phs003125',
                    officer_sign_date: 'false',
                    studystartdate: '07/01/2021',
                    data_genomic: null,
                    status: 'approved',
                },
                innerHits: null,
                fields: {},
                index: 'study_v002',
                clusterAlias: null,
                sourceAsString:
                    '{"is_multi_center":"false","studystartdate":"07/01/2021","estimated_participants":"Survey","public_access_data":"Human Data; Prospective Sample; Questionnaires/Surveys; SARS-CoV-2 test result","@version":"1","pi_assistant_name":"example@example.com","types":"false","status":"approved","pi_name":"John Doe","pi_assistant_email":"Pennington Biomedical Research Center","dcc":"RADx-UP","pi_email":"example@example.com","@timestamp":"2023-07-05T20:57:13.218Z","phs":"phs003125","pi_sign_date":"Jane Doe","po_name":"98","data_genotype":null,"source":"Jane Doe","data_sample_types":null,"officer_sign_date":"false","title":"Engaging Church Health Ministries to Decrease SARS-CoV-2 Vaccine Hesitancy in Underserved Populations in Baton Rouge","unrestricted_access":"NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES","pi_institution":null,"data_general_types":"Questionnaires/Surveys, SARS-CoV-2 test result","multi_center_sites":null,"study_id":189,"needs_institutional_certifications":null,"description":"In the US, COVID-19 unveiled a disproportionate health burden in low income and underserved segments of society.  In Louisiana, some of the greatest health and economic consequences are evident in our Black communities. Furthermore, despite the widespread availability of SARS-CoV-2 vaccines, approximately 30% of the US population reports that they will not get vaccinated, and Black citizens and those with lower socio-economic status are more likely to have vaccine hesitancy. Thus, there is an urgent need to address vaccine hesitancy within the context of the COVID-19 pandemic and the current testing environment. The Louisiana Clinical and Translational Science (LA CaTS) Center provides the essential infrastructure and key foundational support for biomedical research in our region and is uniquely positioned to lead a community-engaged research project to determine solutions to decrease vaccine hesitancy and improve testing rates in our most underserved populations. Faith-based organizations (churches, mosques, temples, etc.) are trusted sources of information, especially among Black communities, and may represent an opportunity to convey accurate, unbiased health information regarding COVID-19 vaccinations and testing to the community. Many Black churches have well-developed health ministries that integrate faith and health for their members and the communities they serve. We will use a mixed-methods study design to determine the effectiveness of training church health ministers to educate their congregations about the safety and efficacy of COVID-19 vaccines for decreasing vaccine hesitancy and improving testing knowledge in underserved Black communities. We will randomize 98 participants from five churches to an intervention group that will receive counseling from their health ministers on the benefits of getting vaccinated and tested, or to a delayed intervention control group. The effects of the intervention on the primary outcome, vaccine hesitancy measured by a questionnaire, will be administered to both groups after three weeks. Following the three-week control period, the delayed intervention control group will also receive the intervention and again be administered the questionnaire. We will then conduct focus groups among a sub-sample of participants to obtain more granular information on sources of vaccine hesitancy and for their vaccine-related decisions. The achievement of the study’s goals will significantly increase our understanding of vaccine hesitancy within Black urban communities in Louisiana. Our results will inform the development of targeted interventions to increase vaccine coverage in the large, underserved populations across the American South.","studyenddate":"06/30/2022","data_genomic":null,"institutes_supporting_study":"true","subject":"This is a randomized vaccine hesitancy intervention conducted in churches by church health ministers We will collect data from surveys and SARS-CoV-2 testing","data_sequencing":null}',
                rawSortValues: [],
                sourceRef: {
                    fragment: true,
                },
                fragment: false,
            },
            {
                score: 1,
                id: '9CbYJ4kBcyt0zD4LTkyX',
                type: null,
                nestedIdentity: null,
                version: -1,
                seqNo: -2,
                primaryTerm: 0,
                highlightFields: {},
                sortValues: [],
                matchedQueries: [],
                explanation: null,
                shard: null,
                sourceAsMap: {
                    data_genotype: null,
                    studyenddate: '08/31/2022',
                    pi_name: 'John Doe',
                    dcc: 'RADx-UP',
                    unrestricted_access: 'National Institute on Aging',
                    pi_email: 'example@example.com',
                    subject: 'Survey data',
                    description:
                        'The rapid spread of the SARS-CoV-2 virus has greatly impacted underserved populations. This project aims to understand social and behavioral determinants of COVID-19 testing and variations within sub-groups of this population. In partnership with the largest federally qualified health center in the United States, we will collect survey data and conduct a randomized experiment on 2,160 individuals (540 families) to evaluate the effectiveness of risk-based messaging and incentives that promote repeated testing for SARS-CoV-2 antibodies. In a 2 x 2 (Messaging x Incentive) factorial experiment, participants are randomized to receive personalized messaging promoting repeated testing. Messaging will focus upon either (1a)   household risk or (1b)  personal risk of COVID-19. They are also randomly assigned to an incentive condition that (2a) insures against losing baseline rewards for initial testing, or (2b) that enters them into a bonus lottery with a small chance to win $150 if they complete both tests. Both the insurance and lottery conditions carry the same incentive costs. Our previous work in similar populations demonstrated that adherence to planned health behaviors is higher with insurance-based incentives than cash payments of equal value.This experiment compares insurance-based incentives to lottery incentives that have been shown to be effective in multiple contexts.  Finally, we evaluate if social and behavioral determinants of health result in heterogeneous treatment effects that can inform customization of incentive offerings in future programs devoted to increasing uptake of testing or vaccinations among underserved populations.',
                    pi_sign_date: 'Jane Doe',
                    source: 'Jane Doe',
                    study_id: 111,
                    title: 'Use of Behavioral Economics in Repeat SARS-CoV-2 Antibody Testing in Disadvantaged Communities',
                    data_sequencing: null,
                    public_access_data: 'Human Data; Prospective Sample; Questionnaires/Surveys',
                    estimated_participants: 'Survey',
                    '@version': '1',
                    po_name: '2000',
                    data_general_types: 'Questionnaires/Surveys',
                    needs_institutional_certifications: null,
                    types: 'false',
                    multi_center_sites: null,
                    pi_assistant_name: 'example@example.com',
                    pi_institution: null,
                    data_sample_types: null,
                    institutes_supporting_study: 'true',
                    '@timestamp': '2023-07-05T20:57:13.198Z',
                    is_multi_center: 'false',
                    pi_assistant_email: 'University of Southern California',
                    phs: 'phs002704',
                    officer_sign_date: 'false',
                    studystartdate: '09/30/2020',
                    data_genomic: null,
                    status: 'approved',
                },
                innerHits: null,
                fields: {},
                index: 'study_v002',
                clusterAlias: null,
                sourceAsString:
                    '{"is_multi_center":"false","studystartdate":"09/30/2020","estimated_participants":"Survey","public_access_data":"Human Data; Prospective Sample; Questionnaires/Surveys","@version":"1","pi_assistant_name":"example@example.com","types":"false","status":"approved","pi_name":"John Doe","pi_assistant_email":"University of Southern California","dcc":"RADx-UP","pi_email":"example@example.com","@timestamp":"2023-07-05T20:57:13.198Z","phs":"phs002704","pi_sign_date":"Jane Doe","po_name":"2000","data_genotype":null,"source":"Jane Doe","data_sample_types":null,"officer_sign_date":"false","title":"Use of Behavioral Economics in Repeat SARS-CoV-2 Antibody Testing in Disadvantaged Communities","unrestricted_access":"National Institute on Aging","pi_institution":null,"data_general_types":"Questionnaires/Surveys","multi_center_sites":null,"study_id":111,"needs_institutional_certifications":null,"description":"The rapid spread of the SARS-CoV-2 virus has greatly impacted underserved populations. This project aims to understand social and behavioral determinants of COVID-19 testing and variations within sub-groups of this population. In partnership with the largest federally qualified health center in the United States, we will collect survey data and conduct a randomized experiment on 2,160 individuals (540 families) to evaluate the effectiveness of risk-based messaging and incentives that promote repeated testing for SARS-CoV-2 antibodies. In a 2 x 2 (Messaging x Incentive) factorial experiment, participants are randomized to receive personalized messaging promoting repeated testing. Messaging will focus upon either (1a)   household risk or (1b)  personal risk of COVID-19. They are also randomly assigned to an incentive condition that (2a) insures against losing baseline rewards for initial testing, or (2b) that enters them into a bonus lottery with a small chance to win $150 if they complete both tests. Both the insurance and lottery conditions carry the same incentive costs. Our previous work in similar populations demonstrated that adherence to planned health behaviors is higher with insurance-based incentives than cash payments of equal value.This experiment compares insurance-based incentives to lottery incentives that have been shown to be effective in multiple contexts.  Finally, we evaluate if social and behavioral determinants of health result in heterogeneous treatment effects that can inform customization of incentive offerings in future programs devoted to increasing uptake of testing or vaccinations among underserved populations.","studyenddate":"08/31/2022","data_genomic":null,"institutes_supporting_study":"true","subject":"Survey data","data_sequencing":null}',
                rawSortValues: [],
                sourceRef: {
                    fragment: true,
                },
                fragment: false,
            },
        ],
        totalHits: {
            value: 163,
            relation: 'EQUAL_TO',
        },
        maxScore: 1,
        sortFields: null,
        collapseField: null,
        collapseValues: null,
        fragment: true,
    },
    numReducePhases: 1,
    failedShards: 0,
    timedOut: false,
    terminatedEarly: null,
    took: {
        seconds: 0,
        days: 0,
        hours: 0,
        minutes: 0,
        millis: 19,
        nanos: 19000000,
        stringRep: '19ms',
        minutesFrac: 0.00031666666666666665,
        hoursFrac: 0.000005277777777777778,
        millisFrac: 19,
        secondsFrac: 0.019,
        microsFrac: 19000,
        micros: 19000,
        daysFrac: 2.199074074074074e-7,
    },
    suggest: null,
    aggregations: null,
    profileResults: {},
    fragment: false,
};
