/* eslint-disable max-len */
import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import classes from './About.module.scss';
import Banner from '../../components/Banner/Banner';
import Card from '../../components/Card/Card';
import { useRouter } from 'next/router';
import Image from 'next/legacy/image';
import renciLogo from './images/renci-logo 2.png';
import bahLogo from './images/Picture1 1.png';
import stanfordLogo from './images/BMIR_logo_stack_85bc295d4b 1.png';
import ExternalLinkIcon from '../../components/ExternalLinkIcon/ExternalLinkIcon';
/**
 * View for the News Page
 * @property {Array<Object>} news - List of all news
 * @returns {Node} object rendering news
 */

const About = (props) => {
    const router = useRouter();

    return (
        <>
            <Banner
                title="Learn About RADx Data Hub"
                path={router.asPath}
                variant="virus4"
                ariaLabel="Learn About RADx Data Hub Breadcrumb"
            />

            <Container className={classes.Container}>
                <Row className={`${classes.Row} whiteTextBackground`}>
                    <h2 className={classes.black}>About RADx Data Hub</h2>

                    <Col lg={8}>
                        <p>
                            The NIH Rapid Acceleration of Diagnostics Data Hub (RADx Data Hub) supports researchers in accessing curated and
                            de-identified COVID-19 data, allowing them to find, aggregate, and perform data analyses in a cloud-enabled
                            platform.
                        </p>
                        <p>
                            The RADx Data Hub supports efforts to understand COVID-19 and factors associated with disparities in COVID-19
                            morbidity and mortality in underserved and vulnerable populations. To do this, the RADx Data Hub seeks to
                            accelerate scientific solutions and innovations in the development, commercialization, and implementation of
                            technologies for COVID-19 testing by providing de-identified COVID-19-related data, algorithms, and other
                            capabilities generated by various digital health solutions and technologies.
                        </p>
                        <p>
                            The RADx Data Hub allows researchers to share the results of their analyses and relevant data, collaborate with
                            other members of the research community, and make use of AI machine learning algorithm research that supports
                            their individual contributions.
                        </p>
                    </Col>

                    <Col lg={4}>
                        <Image priority src="/images/radx-4-collage.png" width="1500px" height="532px" />
                    </Col>
                </Row>
                <Row className={`${classes.Row} whiteTextBackground`}>
                    <h3 className={classes.black}>RADx Coordinating and Data Collection Centers</h3>

                    <p className={classes.section}>
                        Sharing RADx data and results as rapidly as possible will allow researchers to conduct secondary analyses and
                        address issues related to the difficulties with the detection and prevention of community spread for COVID-19,
                        ultimately leading to rapid development of new technologies needed to move the nation beyond the pandemic. As such,
                        the RADx Data Hub supports the following RADx Coordinating and Data Collection Centers (C)DCCs, which collect and
                        share a wide variety of COVID-related research data and technologies:
                    </p>
                    <div className={classes.indent}>
                        <h5 className={classes.black}>RADx Tech</h5>
                        <hr className={classes.separator} />
                        <p className={classes.section}>
                            The RADx Tech initiative aims to speed the development, validation, and commercialization of innovative
                            point-of-care and home-based tests and improve clinical laboratory tests that can directly detect the COVID-19
                            virus. RADx Tech has expanded the NIH’s National Institute of Biomedical Imaging and Bioengineering (NIIBIB)
                            Point-of-Care Technologies Research Network (POCTRN) that is using a flexible, rapid process to fund and enhance
                            technology designs at key stages of development with expertise from technology innovators, clinical testing,
                            regulatory affairs, entrepreneurs, and business leaders. Learn more at{' '}
                            <a href="https://www.covid19testus.org" target="_blank" rel="noreferrer">
                                https://www.covid19testus.org
                            </a>
                        </p>
                        <h5 className={classes.black}>RADx Underserved Populations (RADx-UP)</h5>
                        <hr className={classes.separator} />
                        <p className={classes.section}>
                            The overarching goal of the RADx-UP initiative is to understand the factors associated with disparities in
                            COVID-19 morbidity and mortality in order to reduce health disparities for underserved and vulnerable
                            populations, who are disproportionately affected by the highest infection rates of COVID-19 and are most at risk
                            for complications or poor outcomes from the pandemic. Learn more at{' '}
                            <a href="https://radx-up.org/" target="_blank" rel="noreferrer">
                                https://radx-up.org/
                            </a>
                        </p>
                        <h5 className={classes.black}>RADx Radical (RADx-rad)</h5>
                        <hr className={classes.separator} />
                        <p className={classes.section}>
                            The RADx-rad effort is aimed to address usability, accessibility, and accuracy gaps in COVID-19 testing by
                            supporting existing and new, non-traditional approaches, including rapid detection devices and home-based
                            testing technologies. This work may also lead to new ways of identifying SARS-CoV-2 virus and its variants.
                            Learn more at{' '}
                            <a href="https://www.radxrad.org/" target="_blank" rel="noreferrer">
                                https://www.radxrad.org/
                            </a>
                        </p>
                        <h5 className={classes.black}>RADx Digital Health Technologies (RADx DHT)</h5>
                        <hr className={classes.separator} />
                        <p className={classes.section}>
                            The RADx DHT goal is to develop digital health solutions, including user-friendly tools such as smartphone apps,
                            wearable devices, and software, to identify and trace contacts of infected individuals, track verified COVID-19
                            test results, and monitor health status of infected and potentially infected individuals. Learn more at{' '}
                            <a href="https://rapids.ll.mit.edu/" target="_blank" rel="noreferrer">
                                https://rapids.ll.mit.edu/
                            </a>
                        </p>
                    </div>
                </Row>
                <Row>
                    <Col lg={12}>
                        <Card title="About RADx Data Hub Partners" headerImg="/images/large1.png" variant="info" bkgdColor="#EDEDED">
                            <div className="pb-3">
                                <p>
                                    A partnership of Stanford University (Stanford), Booz Allen Hamilton, and the Renaissance Computing
                                    Institute (RENCI) assists the NIH with three key aspects of the RADx Data Hub:
                                </p>
                                <div className={classes.list}>
                                    <ul>
                                        <li>
                                            <span className={classes.bold}>Data Hub Development:</span> Develop and enhance the Data Hub
                                            functions that store, share, and provide data analysis and utilization capabilities{' '}
                                            <span className={classes.bold}>
                                                (
                                                <a href="https://www.boozallen.com/" target="_blank" rel="noreferrer">
                                                    Booz Allen Hamilton
                                                </a>
                                                <ExternalLinkIcon />)
                                            </span>
                                        </li>
                                        <li>
                                            <span className={classes.bold}>Data Management:</span> Translate proposed standards for data and
                                            metadata into computational form, validate data quality, and enable greater use of common data
                                            elements, standardization, and harmonization{' '}
                                            <span className={classes.bold}>
                                                (
                                                <a href="https://bmir.stanford.edu/" target="_blank" rel="noreferrer">
                                                    Stanford
                                                </a>
                                                <ExternalLinkIcon />)
                                            </span>
                                        </li>
                                        <li>
                                            <span className={classes.bold}>Program Management:</span> Establish and maintain effective
                                            cross-disciplinary program management, including technical development, data coordinating center
                                            connectivity, researcher engagement, and training{' '}
                                            <span className={classes.bold}>
                                                (
                                                <a href="https://renci.org/" target="_blank" rel="noreferrer">
                                                    RENCI
                                                </a>
                                                <ExternalLinkIcon />)
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                                <div className={classes.partners}>
                                    <Image src={stanfordLogo} alt="Stanford Logo" />
                                    <Image src={bahLogo} alt="Stanford Logo" />
                                    <Image src={renciLogo} alt="Stanford Logo" />
                                </div>
                            </div>
                        </Card>
                    </Col>
                </Row>
            </Container>
        </>
    );
};

export default About;
